apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-agenda
  namespace: StudioBarber
  labels:
    app: reservas-agenda-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservas-agenda-service
  template:
    metadata:
      labels:
        app: reservas-agenda-service
    spec:
      containers:
        - name: reservas-agenda-service
          # nombre local de la imagen -> agenda-service-local:latest (igual siempre)
          image: us-central1-docker.pkg.dev/studiobarber-480215/repo-agenda/agenda-service:v1.0.0
          imagePullPolicy: Always  # nos aseguramos que siempre use la ultima version de la imagen
          ports:
            - containerPort: 8083
              protocol: TCP

# cambios en el codigo = nueva imagen = nueva version vX.0.0
# pasos para subir a Artifact Registry
# 1. docker build -t agenda-service-local:latest . -> contruir imagen local
# 2. docker tag agenda-service-local:latest us-central1-docker.pkg.dev/studiobarber-480215/repo-agenda/agenda-service:v1.0.1 -> tag para subir a AR
# 3. docker push us-central1-docker.pkg.dev/studiobarber-480215/repo-agenda/agenda-service:v1.0.0 -> subir imagen